.github/workflows/test.yml
node のサポートバージョンから 10 系を削除、16 系を追加しました。
=> chore: upgrade supported node version

.github/workflows/test.yml
Node.js v12 のテストを削除します。
v12 で動くことを保証しなくなるので BREAKING CHANGE とします。
=> test!: テストから Node.js v12 の環境を削除

package.json, packages/create-lint-set/LICENSE, packages/create-lint-set/README.md, packages/create-lint-set/package.json, packages/create-lint-set/src/createLintSet.ts, packages/create-lint-set/src/index.ts, packages/create-lint-set/src/items.ts, packages/create-lint-set/src/templates/eslint/.eslintrc, packages/create-lint-set/src/templates/prettier/.prettierrc.js, packages/create-lint-set/src/templates/stylelint/.stylelintrc, packages/create-lint-set/src/templates/textlint/.textlintrc.yml, packages/create-lint-set/tsconfig.json, packages/tsconfig.json, yarn.lock
create-lint-set という名前で、SmartHR プロダクトで使っている lint ツールの一括インストール CLI を追加しました。
READEME.md に記載のとおりですが、`$ npx @smarthr/create-lint-set` を実行することで
- eslint
- prettier
- stylelint
- textlint
関連のパッケージが、最低限の設定ファイルとともにローカルにインストールされるイメージです。
まず、実行対象となる適当なディレクトリを作成します。
`$ mkdir hoge`
`$ cd hoge`
`$ npm init -y`
その後、ローカル開発環境では下記のいずれかを実行します。
- tamatebako で `$ yarn build` 実行後に `$ node ~/your/path/tamatebako/create-lint-set/lib/index.js`
- `$ npx ts-node ~/your/path/tamatebako/create-lint-set/src/index.ts` (**ts-node を使う場合は ts ファイルを直接実行するので yarn build は不要**)
`hoge` ディレクトリ内にパッケージがインストールされ、各種設定ファイルが作成されていることを確認します。
=> lint 関連ツールを一括でインストールするための CLI パッケージを追加

packages/wareki/src/__tests__/index.test.ts, packages/wareki/src/index.ts
- warekiを使う際、resultがinvalid dateになることが間々ある
- その場合、全角->半角変換済みの値をday.jsなどに食わせるfallbackを行ったりする
- wareki内で上記変換は実施済みのため、resultに含めてreturnすることで使いやすくしたい
=> feat: warekiの各メソッドのfallbackを書きやすくするため半角変換された日付テキストを常に返す

packages/next-auth/src/RedisAdapter.ts
NextAuth の upstash redis adapter のコードをコピーして細部を変更しただけのコードに対して、コピー元の URL とライセンスを記載
=> chore: 参照元の next-auth のライセンスを追記

packages/next-auth/src/SmarthrProvider.ts
`@smarthr/next-auth` を使ってログインした際、アクセストークン・リフレッシュトークンに加えてアクセストークンの有効期限も取得したい
OAuth プロバイダがログインに成功した際に返す下記の情報を利用して、[Next-Auth が自動的に計算](https://github.com/nextauthjs/next-auth/blob/c7dec376a1272a0877c7e6fb2fc4173f08369f9f/packages/core/src/lib/oauth/callback.ts#L169-L172)した `expires_at` を返せるようにする。
OAuth プロバイダがログインに成功した際に返すデータ:
```js
{
access_token: '[FILTERD]',
refresh_token: '[FILTERD]',
token_request_subdomain: null,
scope: '[FILTERD]',
token_request_tenant_id: null,
token_type: 'Bearer',
expires_in: 86400  // この値を `tokens` に追加する
}
```
`expires_in` を設定することで Next-Auth 側で `expires_at` が計算されて下記の account オブジェクトが返る:
```js
{
provider: 'smarthr',
type: 'oauth',
providerAccountId: '[FILTERD]',
access_token: '[FILTERD]',
refresh_token: '[FILTERD]',
expires_at: 1686733494
}
```
=> feat: @smarthr/next-auth ログインに成功した時、アクセストークンの有効期限をアカウント情報に追加する

packages/next-auth/src/SmarthrProvider.ts
- yosegiやkatanaなど、NextAuthを利用しているプロダクトで `OAuthAccountNotLinked` エラーが度々発生していました
- トライアルなどで一度プラスアプリにログインしたことがある状態で、そのログイン状態がRedisに残ったまま同メールアドレス・別アカウントでプラスアプリにアクセスした場合などにこのエラーになります
- このエラーが発生した場合、ユーザー側では対応できず、プロダクトチーム側でRedisのキーを手動で削除する対応が必要でした😭
- 詳しい経緯と内容は以下のDocBaseにまとめられています
- [[yosegi] 20230817_認証エラー(OAuthAccountNotLinked)が発生してログインできない - DocBase](https://smarthr-inc.docbase.io/posts/3075405)
- 以下のDiscussionで対応案を検討していました
- https://github.com/kufu/yosegi/discussions/2292
- 検討の結果、SmarthrProviderにオプショナルな引数を追加し、それがtrueだった場合に`email`に`uuid()`を一意のidとして詰める、という対応でどうじゃろかと思っています...！
- 検討の詳細はDiscussionに書いています
- 1/11のフロントエンド定例でも共有し、概ね良さそうという反応をもらってます
- 議事録: https://smarthr-inc.docbase.io/posts/3247534#smarthrprovider%E3%81%AB%E9%9D%9E%E7%A0%B4%E5%A3%8A%E3%81%AA%E5%A4%89%E6%9B%B4%E3%82%92%E3%81%84%E3%82%8 …
=> OAuthAccountNotLinkedエラー回避のため、emailが重複しないように設定するオプションを追加する

.github/workflows/lint.yml, .github/workflows/test.yml
tamatebakoでテストに使っているnodeのバージョンが16.xと18.xだったのですが、すでに16.xはメンテナンスが終了してサポート対象外になっているので修正したい
https://nodejs.org/en/about/previous-releases
ACTIVEの20.xと、MAINTENANCEの18.xで `test` と `lint` の CI が動くようにしました。
=> node 16.xをテスト対象外にし、20.xをテスト対象に追加

packages/create-lint-set/src/items.ts
`npx @smarthr/create-lint-set` を実行するとエラーとなります。
```
% npx @smarthr/create-lint-set
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: xxx@1.0.0
npm error Found: stylelint@14.16.1
npm error node_modules/stylelint
npm error   dev stylelint@"*" from the root project
npm error   peer stylelint@">= 11.x < 15" from stylelint-config-prettier@9.0.5
npm error   node_modules/stylelint-config-prettier
npm error     dev stylelint-config-prettier@"*" from the root project
npm error
npm error Could not resolve dependency:
npm error dev stylelint-config-smarthr@"*" from the root project
npm error
npm error Conflicting peer dependency: stylelint@16.7.0
npm error node_modules/stylelint
npm error   peer stylelint@"^16.0.0" from stylelint-config-smarthr@3.0.1 …
```
=> パッケージの情報が古いため、create-lint-set が動作しなくなっている問題を修正

packages/next-auth/src/RedisAdapter.ts
- Redisデータの有効期限 (TTL) はデフォルトだと無期限のため、オプション機能でログインすると明示的に削除しない限り永久にユーザ情報が残る
- 基本機能から発行されたアクセストークンは7日間で失効する仕組みなので、意味のないデータが溜まる状態になっていそう
- 固定値で7日間を期限として設定しました
- 書き込みの後処理としてTTLの設定を追加しています
- RedisにはグローバルなTTLを設定する機構がないので、個別の書き込みすべてに適用しています
- 個別に異なる期限を設定したいケースが思いつかなかったので呼び出し側 (アプリ) で値を上書きするような機構は設けておりません
- 有効期限を保持するためにメモリ使用量が若干増えるらしいです…がデータ保存に比べれば誤差の範疇だと思います
コードレビューのみで大丈夫だと思います
- 書き込み処理すべてにTTLが指定されていること
- (= `Redis.set` ではなく独自実装の `set` が使われていること)
- 認証時のデータフローを変えてしまう差分がないこと
=> NextAuthがRedisに保存する認証情報に有効期限を設定したい

lerna.json, package.json, tsconfig.json, yarn.lock
* master最新で `versionup` スクリプトが実行できない状態でした
* lerna 6系 + prettier 3系の組み合わせがダメっぽい雰囲気でした (ref: https://github.com/lerna/lerna/issues/3806)
* lernaをバージョンアップしました
* `yarn upgrade lerna@latest` で最新版にアップデートしました
* `./node_modules/.bin/lerna repair` で各種設定をアップデートに追従しています
* 現状unmet dep的な警告は出てないので動きそう…な気はしています
* ただ動作確認はできておりませんので、マージして再度リリースを試みダメだったら追加対応します 🥺
=> lernaをアップデートしたい

packages/prettier-config-smarthr/CHANGELOG.md, packages/prettier-config-smarthr/LICENSE, packages/prettier-config-smarthr/README.md, packages/prettier-config-smarthr/index.json, packages/prettier-config-smarthr/package.json, pnpm-lock.yaml
https://github.com/kufu/prettier-config-smarthr のリポジトリは閉じて、tamatebako 上で管理する方針になったのでファイルを移動しました。
リポジトリの変更に伴って package.json の記述を一部[もとのファイル](https://github.com/kufu/prettier-config-smarthr/blob/main/package.json)から変更しています。(パスの変更や、devDependencies の削除など)
このプルリクがマージされたら、https://github.com/kufu/prettier-config-smarthr のリポジトリに関しては README.md に管理が tamatebako になった旨を記載したうえでアーカイブする予定です。
=> chore: https://github.com/kufu/prettier-config-smarthr からファイルを移動

CONTRIBUTING.md, package.json, packages/create-lint-set/package.json, packages/next-auth/package.json, packages/use-bulk-check/package.json, packages/use-virtual-scroll/package.json, packages/wareki/package.json
- ルートの package.json から`prerelease` コマンドを削除して、各パッケージに `prerelease` コマンドを追加した
- 理由は、ルートの package.json から`prerelease` コマンドを実行するタイミングが明示されていないわりに、これを実行しないと `build` を実行したときに (lib ディレクトリが既に存在するなどの理由で) 失敗するパッケージが存在していたからです。
- `build` を実行するタイミングで `prerelease` がやっていたことと同じことを実行するように変更して、常に `build` コマンドが成功するようにしました。
- ルートの `start` コマンドを `dev` コマンドの変更した
- 理由は、SmartHR 社のプロダクト・ライブラリでは基本的にこういったコマンドには `dev` を割り当てることが慣習になっているからです。
=> chore: npm コマンド周りで気になったところを改善した

package.json, packages/stylelint-config-smarthr/CHANGELOG.md, packages/stylelint-config-smarthr/LICENSE, packages/stylelint-config-smarthr/README.md, packages/stylelint-config-smarthr/index.js, packages/stylelint-config-smarthr/package.json, packages/stylelint-config-smarthr/test/__snapshots__/run.test.js.snap, packages/stylelint-config-smarthr/test/fixtures/index.tsx, packages/stylelint-config-smarthr/test/lib/runLint.js, packages/stylelint-config-smarthr/test/run.test.js, packages/stylelint-config-smarthr/vitest.config.ts, pnpm-lock.yaml
https://github.com/kufu/stylelint-config-smarthr のリポジトリは閉じて、tamatebako 上で管理する方針になったのでファイルを移動しました。
リポジトリの変更に伴って package.json の記述を一部[もとのファイル](https://github.com/kufu/stylelint-config-smarthr/blob/master/package.json)から変更しています。(パスの変更や、不要な npm scripts の削除など)
このプルリクがマージされたら、https://github.com/kufu/stylelint-config-smarthr のリポジトリに関しては README.md に管理が tamatebako になった旨を記載したうえでアーカイブする予定です。
=> chore: https://github.com/kufu/stylelint-config-smarthr からファイルを移動

.github/workflows/release.yml, .release-please-manifest.json, release-please-config.json
現状のリリースフローは手元で pnpm version を実行した後 pnpm publish を実行するというものですが、この運用には下記のような課題があるかなと思います。
- リリースされるものがなにか分かりづらい
- 今回のリリースで何がリリース対象になるのかは、pnpm version を実行して changelog を生成するまではコミットやプルリクを追わないといけなく、直感的に知る方法がない
- npm に publish する権限がないとリリースできない
- リリースしたい場合は npm の SmartHR の organization に追加してもらう必要があります
- リリースのために手元でコマンドを実行するのがシンプルに面倒
これらの問題によって、なんとなく tamatebako が触りづらい気持ちになり、メンテナンスが滞りがちなところがあると思っています。
release-please という github actions を使うと、下記のような運用になるので、上記の課題が解決されます。
- プルリクがマージされると conventional commits の内容に応じてリリース用のプルリクが作成される
- そのプルリクの description を見てリリース内容を確認する
- そのプルリクをマージすることでリリースが行われる
リリースされるものがわかりやすい & リリースしやすい仕組みになるので、幸せになれる気がしています！
リポジトリを fork して具体的な挙動を確かめています 👇 
まずはこのプルリクとほぼ同じ内容のものをマージしました。(publish 部分だけ実行されないように書き換えています)
https://github.com/Tokky0425/tamatebako/pull/1
次に、`fix!` の prefix …
=> chore: please-release でリリースできるようにした

packages/eslint-plugin-smarthr/rules/a11y-input-in-form-control/index.js, packages/eslint-plugin-smarthr/test/a11y-input-in-form-control.js
- type="hidden" が指定されている場合の対応を追加します
- hiddenの場合、labelは不要なため必須判定から除外します
=> feat: a11y-input-in-form-controlでtype="hidden"の場合の判定を追加

packages/eslint-plugin-smarthr/rules/a11y-delegate-element-has-role-presentation/index.js, packages/eslint-plugin-smarthr/rules/a11y-input-has-name-attribute/index.js, packages/eslint-plugin-smarthr/rules/a11y-input-in-form-control/README.md, packages/eslint-plugin-smarthr/rules/a11y-input-in-form-control/index.js, packages/eslint-plugin-smarthr/rules/a11y-prohibit-input-placeholder/index.js, packages/eslint-plugin-smarthr/test/a11y-delegate-element-has-role-presantation.js, packages/eslint-plugin-smarthr/test/a11y-input-has-name-attribute.js, packages/eslint-plugin-smarthr/test/a11y-input-in-form-control.js, packages/eslint-plugin-smarthr/test/a11y-prohhibit-input-placeholder.js
- smarthr-ui/WarekiPicker が導入されたので対応します
- 基本的にDatePickerと全く同じコンポーネントのため、そのままDatePicker or WarekiPickerどちらでも同じチェックを実行するようにしています
=> feat: a11y系のルールをsmarthr-ui/WarekiPickerに対応させる

.github/workflows/release.yml
[リリースでコケた](https://github.com/kufu/tamatebako/actions/runs/12664241504/job/35292061540)のでそれの修正対応です。
[npmレジストリへのパッケージの公開](https://docs.github.com/ja/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) に書いてある
> 資格情報を適切に構成するには、setup-node で registry-url を https://registry.npmjs.org/ に設定する必要があることに注意してください。
が反映されていないのが原因なのではないかなと思っています。
`registry-url` があると、
```
//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
registry=https://registry.npmjs.org/
```
の記述が含まれる .npmrc を作成してくれるようです。
実装: https://github.com/actions/setup-node/blob/48b90677b6048efbc723b11a94acb950d3f1ac36/src/main.ts#L58-L60
=> chore: setup-node 時に registry-url の指定を追加

packages/eslint-config-smarthr/configs/eslint.js, packages/eslint-config-smarthr/configs/react.js, packages/eslint-config-smarthr/package.json, packages/eslint-config-smarthr/test/__snapshots__/snapshot.test.js.snap
- react 17+以降のeslintルールに対応し、不要なルールをOFFにしたいです。
- 以下のルールがデフォルトでエラーからOFFにした。
- [react/jsx-uses-react](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md)
- [react/react-in-jsx-scope](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md)
- `import React from 'react';` のようにデフォルトインポートを使った場合はエラーになるようにした。
- ref: https://github.com/kufu/tamatebako/pull/499#discussion_r1936598772
react 17以前は `import React from 'react'` の記述が必須でした。実際、eslint-plugin-reactでは [react/react-in-jsx-scope](https://github.com/jsx-eslint/eslint-plugin-react/blob/e6b5b41191690ee166d0cca1e9db27092b910f03/docs/rules/react-in-jsx-scope.md)のルールがデフォルトでONです。
[react 17以降は `import React from 'react'` …
=> feat(eslint-config-smarthr)!: react 17+以降のルールに対応した

.github/workflows/release.yml
[corepack起因](https://github.com/nodejs/corepack/issues/612)でnpmへの[publishに失敗](https://github.com/kufu/tamatebako/actions/runs/13126270687/job/36623133718)していた問題へ対応しました。
=> ci: publishに失敗しないようにcorepackの有効化方法を変えた

packages/next-auth/src/SmarthrProvider.ts
`@smarthr/next-auth` を使用しているプラスアプリでは、ログイン時に渡される profile の role.session_timeout_in を redis の expire に設定することで、SmartHR で設定している権限のタイムアウトの設定をプラスアプリ側でも引き継ぐ実装になっています。
しかし、`@smarthr/next-auth` 側で profile に role を渡していなかったため、プラスアプリ側で role.session_timeout_in が取得できておらず、タイムアウトの設定が引き継がれない状態になってしまっていました。
直したい。
=> :bug: profile に role が含まれていなかったので role.session_timeout_in を追加

.github/workflows/titleCheck.yml
smarthr-ui で導入されているもの 👇  をほぼそのまま持ってきました (if 条件の部分だけ不要なので削除しています)
https://github.com/kufu/smarthr-ui/blob/1c9462425518d2628061279ea737d3cdd610e342/.github/workflows/titleCheck.yml
このプルリク上で、`chore:` をタイトルから消すと CI が落ちることを確認済みです 👁️
=> chore: プルリクタイトルが conventional commits に従っているかをチェックするようにした

packages/eslint-config-smarthr/index.js, packages/eslint-config-smarthr/package.json, packages/eslint-config-smarthr/test/__snapshots__/snapshot.test.js.snap, pnpm-lock.yaml
- イベントハンドラ外からのe.currentTarget参照を避けるルールを有効化します
- このチェックの対象となるコードは、ランダムで成否が変わり気づきにくいため
=> feat: smarthr/best-practice-for-async-current-target を有効にする

packages/eslint-plugin-smarthr/rules/a11y-anchor-has-href-attribute/index.js
a11y-anchor-has-href-attribute のルールでは package.json に react-router-dom があれば `href` ではなく `to` があることを検証するような処理になっていますが、React Router は v7 から react-router-dom のパッケージを必要としなくなっているので、この判定が正しく効かない状態になっています。そのため、react-router の有無によって判別をするコードに変更しました。(v6 以前の場合でも、react-router の有無による判別で問題ないので、react-router-dom による判定は削除しています)
=> fix: a11y-anchor-has-href-attribute での特殊分岐条件を react-router-dom から react-router に変更

packages/eslint-config-smarthr/package.json, pnpm-lock.yaml
- eslint-plugin-smarthr v1.8.1
- https://github.com/kufu/tamatebako/releases/tag/eslint-plugin-smarthr-v1.8.1
- eslint-plugin-smarthr v1.8.0
- https://github.com/kufu/tamatebako/releases/tag/eslint-plugin-smarthr-v1.8.0
=> feat: 最新の eslint-plugin-smarthr に追従

packages/i18n/package.json, packages/i18n/src/index.ts, packages/i18n/src/useIntl.test.tsx, packages/i18n/src/useIntl.tsx, pnpm-lock.yaml, tsconfig.json
多言語化対応用の共通モジュールを提供するための `i18n` パッケージにテストを行なうための依存周りを追加しました。
テスト中で`tsx`をインポートするためにルートの`tsconfig.json`に`jsx`設定を追加しています。
APIの実装は追って行なう予定です。
=> feat: i18nパッケージのテスト環境設定を適用

packages/i18n/src/get-locale/getLocale.node.test.ts, packages/i18n/src/get-locale/getLocale.ts, packages/i18n/src/index.ts
getLocaleをサーバサイドで使った場合に、アプリケーションが対応しているロケールであれば利用可能（変更前は必ずデフォルトロケールになる仕様）に変更しました。
cookieやブラウザの言語設定からの取得は非対応のままとしています。
=> feat: getLocaleの一部の判定をサーバサイドでも利用可能にした

packages/i18n/README.md
i18nのREADMEに全体的な使い方（Next.jsのApp Routerでの例）を追記しました。
レビュー用のプレビューは[こちら](https://github.com/kufu/tamatebako/blob/a51f53280e93b229f605dbeee5acfbf1334437d8/packages/i18n/README.md)
=> chore: i18nのREADMEに使い方を追記

packages/tsconfig.json
リリースした i18n パッケージに lib ディレクトリが含まれておらず、プロダクト側から import ができていなかった。
lib ディレクトリが含まれるようにしたい。
`packages/tsconfg.json` で i18n を参照対象に追加。
=> fix: i18n パッケージを ts のビルド対象に含める

packages/eslint-plugin-smarthr/rules/a11y-input-in-form-control/index.js, packages/eslint-plugin-smarthr/test/a11y-input-in-form-control.js
- 現在の入力要素にラベルの設定を促すチェックを修正したい
- 不可視のラベルを設定したい場合、title属性の設定を促していますがこれをやめて必ず FormControl もしくは Fieldset でラップしてもらうようにしたいと考えている
- 現時点のtitleでも問題なくラベルは設定されているが実はこの方法はラベル設定の際、ブラウザが行っているチェック順序の最下位、failsafe的なもの
- この修正が行われた場合、不可視のラベルはdangerouslyTitleHidden属性をtrueにしてもらうことで対応してもらうようになります
- titleやaria-labelなどでa11y nameを設定していても、この修正後はエラーになります
=> feat: a11y-input-form-controlのラベル設定チェックのロジックを変更する
